### ISSUE TITLE
Updating the greasy fork version

### ISSUE THREAD

**Issue by seth--** [convexshiba/down2transmission#1]
I was searching for a script to send magnet links to transmission and found this one, but on greasy fork.

It wasn't working and I ended up re doing this https://github.com/coderant/down2transmission/commit/79b55b06d462d95ef8b8b04e8afbbc17f0f35a41

Today I was about to open a pull request and found I've an old version

Can you update, or at least delete, [this](https://greasyfork.org/es/scripts/28408-down2transmission/versions)?

**Comment by convexshiba** [comment]
Resolve already. Thanks for the fix
